version: '3'
services:
  web:
    image: webdevops/php-apache:7.0
    volumes:
      - ./web:/app
    restart: always
    ports:
      - 80:80
    environment:
      PHP_DATE_TIMEZONE: PRC
      PHP_DISPLAY_ERRORS: 1
      WEB_DOCUMENT_ROOT: /app